select * from ecommerce_schema.users;
select * from ecommerce_schema.supplier;
select * from ecommerce_schema.product;
select * from ecommerce_schema.orders;
select * from ecommerce_schema.orderdetails;
select * from ecommerce_schema.payment;
select * from ecommerce_schema.review;
select * from ecommerce_schema.wishlist;
select * from ecommerce_schema.shipment;